// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWd8nTtbUS32YaG_2r2MJiG400dPShU0',
    appId: '1:837353738902:web:7d6e5b2956e02d1d5128b7',
    messagingSenderId: '837353738902',
    projectId: 'eyra-e159b',
    authDomain: 'eyra-e159b.firebaseapp.com',
    storageBucket: 'eyra-e159b.firebasestorage.app',
    measurementId: 'G-6S4YRPD4GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACYfV_s6QqZzNMFrt7LaQZSeuP4QAhiO8',
    appId: '1:837353738902:android:0069539dd54797f75128b7',
    messagingSenderId: '837353738902',
    projectId: 'eyra-e159b',
    storageBucket: 'eyra-e159b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGb_vgE5ysxmjIjBdaZVkqPY-uyp2Jwc',
    appId: '1:837353738902:ios:f9a5bbabd1069f1f5128b7',
    messagingSenderId: '837353738902',
    projectId: 'eyra-e159b',
    storageBucket: 'eyra-e159b.firebasestorage.app',
    iosBundleId: 'com.example.eyra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGb_vgE5ysxmjIjBdaZVkqPY-uyp2Jwc',
    appId: '1:837353738902:ios:f9a5bbabd1069f1f5128b7',
    messagingSenderId: '837353738902',
    projectId: 'eyra-e159b',
    storageBucket: 'eyra-e159b.firebasestorage.app',
    iosBundleId: 'com.example.eyra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHWd8nTtbUS32YaG_2r2MJiG400dPShU0',
    appId: '1:837353738902:web:d288aa75df37f6cb5128b7',
    messagingSenderId: '837353738902',
    projectId: 'eyra-e159b',
    authDomain: 'eyra-e159b.firebaseapp.com',
    storageBucket: 'eyra-e159b.firebasestorage.app',
    measurementId: 'G-NYVDZ4HMHN',
  );
}
